# @package _global_

model:
  type: Symphonies
  embed_dims: 128
  num_layers: 3
  view_scales: [4, 8, 16]
  # pc_range: [-2, 0, -1, 2, 4, 1]
  # pc_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0] 

  depth:
    depth_model: None
    depth_model_name: zoedepth
    depth_pretrained_resource: local::./checkpoints/depth_anything_metric_depth_indoor.pt
    depth_dataset: nyu

  encoder:
    type: MMDetWrapper
    config_path: maskdino/configs/maskdino_r50_8xb2-panoptic-export.py
    custom_imports: maskdino
    checkpoint_path: checkpoints/maskdino_r50_50e_300q_panoptic_pq53.0.pth
  
  criterions: [ce_ssc, sem_scal, geo_scal, frustum]

optimizer:
  paramwise_cfg:
    - name: encoder.model
      lr_mult: 0.1
