# @package _global_

data:
  datasets:
    type: ScanNetv01
    splits: [train, test]  # replace with kv pairs if specified configs is in need
    version: v_0_1_1
    train_pkl: /share/datasets/version0.1.1/scanNet_train.pkl
    test_pkl: /share/datasets/version0.1.1/scanNet_test.pkl
    root_path: /share/datasets/version0.1.1
    frustum_size: 8
    num_classes: 22
    voxel_size: 0.04
    scene_size: [4,4,2] 
    voxel_shape: [100, 100, 50] 
    pc_range: [-2, 0, -1, 2, 4, 1]
    # pc_range: [-2.08, -0.08, -1.08, 1.92, 3.92, 0.92]
    # img_shape: [630, 476]
    img_shape: [640, 480]
    downscale: 8 ## 视椎损失参数，不修改
    use_tsdf: true
  loader:
    batch_size: 1  # batch size per GPU
    num_workers: 4

model:
  channels: 200
  scene_size: [100, 100, 50]
  volume_scale: 1
  num_classes: 22
  # image_shape: [476, 630]
  image_shape: [480, 640]
  voxel_size: 0.04
  downsample_z: 1

evaluator:
  type: SSCMetrics
  num_classes: 22
