# @package _global_

data:
  datasets:
    type: ScanNet
    splits: [train, test]  # replace with kv pairs if specified configs is in need
    data_root: ./data/occ_scannet
    frustum_size: 8
    voxel_size: 0.08
    # pc_range: [0, 0, 0, 4, 4, 2]
    # pc_range: [-2.08, -0.08, -1.08, 1.92, 3.92, 0.92]
    # img_shape: [630, 476]
    img_shape: [640, 480]
  loader:
    batch_size: 1  # batch size per GPU
    num_workers: 4

model:
  channels: 200
  scene_size: [60, 60, 36] 
  volume_scale: 1
  num_classes: 12
  # image_shape: [476, 630]
  image_shape: [480, 640]
  voxel_size: 0.08
  downsample_z: 1

evaluator1:
  type: SSCMetrics
  num_classes: 12

evaluator2:
  type: SSCMetrics
  num_classes: 12
