# @package _global_

data:
  datasets:
    type: SYNDataVirtualScenes11Class
    splits: [train, test]  # replace with kv pairs if specified configs is in need
    data_root: ./data/honor_data_0920
    depth_root: ./data/honor_data_0920
    label_root: ./data/honor_data_0920
    depth_eval: false
    use_crop: true
    voxel_size: 0.08
    pc_range: [0, 0, 0, 4, 4, 2]
    frustum_size: 8
  loader:
    batch_size: 1  # batch size per GPU
    num_workers: 4

model:
  channels: 200
  scene_size: [50, 50, 25]
  volume_scale: 1
  num_classes: 11
  image_shape: [480, 640]
  voxel_size: 0.08
  downsample_z: 1

evaluator:
  type: SSCMetrics
  num_classes: 11
