# @package _global_

data:
  datasets:
    type: SYNData
    splits: [train, test]  # replace with kv pairs if specified configs is in need
    data_root: ./data/honor_collection_data
    # depth_root: /data2/ylc/codes/Depth-Anything/metric_depth/nyu_no_restraint_depth_visualize
    depth_root: ./data/honor_collection_data
    label_root: ./data/honor_collection_data
    depth_eval: false
    use_crop: true
    voxel_size: 0.08
    pc_range: [0, 0, 0, 4.8, 4.8, 2.88]
    frustum_size: 8
  loader:
    batch_size: 1  # batch size per GPU
    num_workers: 4

model:
  channels: 200
  scene_size: [60, 60, 36]
  volume_scale: 1
  num_classes: 13
  image_shape: [480, 640]
  voxel_size: 0.08
  downsample_z: 1

evaluator:
  type: SSCMetrics
  num_classes: 13
